title = "Wahaab Siddique"
baseurl = "http://www.wahaabsiddique.com"
languagecode = "en"
defaultcontentlanguage = "en"
theme = "hugo-coder"
paginate = 5
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
disqusShortname = "odoo-1"
googleAnalytics = "UA-77218107-6"
pygmentscodefencesguesssyntax = true

[params]
hideCopyright = false
dateformat = "January 2, 2006"
colorscheme = "auto"
favicon_32 = "/images/avatar1.png"
maxSeeAlsoItems = 5
rtl = false
keywords = "blog,developer,personal"
author = "Wahaab Siddique"
info = "Welcome to the official website of Wahaab Siddique."
custom_css = []
avatarurl = "images/avatar1.jpg"
custom_js = []
commit = "https://github.com/luizdepra/hugo-coder/tree/"
hideCredits = false
since = 2019
description = "Wahaab Siddique's personal website"
hideFooter = false
footercontent = ""

[[params.social]]
name = "Github"
icon = "fab fa-github"
weight = 7
url = "https://github.com/wahaab11/"

[[params.social]]
name = "Gitlab"
icon = "fab fa-gitlab"
weight = 6
url = "https://gitlab.com/wahaabsiddique/"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
weight = 1
url = "https://twitter.com/wahaabsiddique/"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/wahaabsiddique/"

[[params.social]]
name = "Medium"
icon = "fab fa-medium"
weight = 5
url = "https://medium.com/@wahaabsiddique"

[[params.social]]
name = "Facebook"
icon = "fab fa-facebook"
weight = 2
url = "https://facebook.com/wahaabsiddiquews"

[[params.social]]
name = "Instagram"
icon = "fab fa-instagram"
weight = 3
url = "https://instagram.com/wahaabsiddique"

[params.plausibleAnalytics]
domain = "wahaabsiddique.com"
serverURL = "https://plausible.io/js/plausible.js"
googleAnalytics = "UA-77218107-6"

[languages]

[languages.en]
languagename = "English"

[languages.en.menu]

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "posts/"
weight = 2

[[languages.en.menu.main]]
name = "Projects"
url = "projects/"
weight = 3

[[languages.en.menu.main]]
name = "Contact me"
url = "contact/"
weight = 5

[languages.pt-br]
languagename = "اردو"
title = "وھاب صدیق"

[languages.pt-br.params]
author = "وھاب صدیق"
info = "میری ویب سائٹ میں خوش آمدید"
description = "میری ویب سائٹ میں خوش آمدید"
keywords = ""
footercontent = ""
since = 2020

[languages.pt-br.menu]

[[languages.pt-br.menu.main]]
name = "میرے بارے میں"
url = "about/"
weight = 1

[[languages.pt-br.menu.main]]
name = "بلاگ"
url = "posts/"
weight = 2

[[languages.pt-br.menu.main]]
name = "پروجیکٹ"
url = "projects/"
weight = 3

[[languages.pt-br.menu.main]]
name = "رابطہ"
url = "contact/"
weight = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"