title = "Wahaab Siddique"
baseurl = "http://www.example.com"
languagecode = "en"
defaultcontentlanguage = "en"
theme = "hugo-coder"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "<div id=\"disqus_thread\"></div> <script>  /** *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS. *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/ /* var disqus_config = function () { this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable }; */ (function() { // DON'T EDIT BELOW THIS LINE var d = document, s = d.createElement('script'); s.src = 'https://coder-4.disqus.com/embed.js'; s.setAttribute('data-timestamp', +new Date()); (d.head || d.body).appendChild(s); })(); </script> <noscript>Please enable JavaScript to view the <a href=\"https://disqus.com/?ref_noscript\">comments powered by Disqus.</a></noscript>                             "

[params]
hideCopyright = false
dateformat = "January 2, 2006"
colorscheme = "auto"
maxSeeAlsoItems = 5
rtl = false
keywords = "blog,developer,personal"
author = "Wahaab Siddique"
info = "Welcome to my website.."
custom_css = []
avatarurl = "images/avatar1.jpg"
custom_js = []
commit = "https://github.com/luizdepra/hugo-coder/tree/"
hideCredits = false
since = 2019
description = "Wahaab Siddique's personal website"
hideFooter = false
footercontent = ""

[[params.social]]
name = "Github"
icon = "fab fa-github"
weight = 1
url = "https://github.com/wahaab11/"

[[params.social]]
name = "Gitlab"
icon = "fab fa-gitlab"
weight = 2
url = "https://gitlab.com/wahaabsiddique/"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
weight = 3
url = "https://twitter.com/wahaabsiddique/"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/wahaabsiddique/"

[[params.social]]
name = "Medium"
icon = "fab fa-medium"
weight = 5
url = "https://medium.com/@wahaabsiddique"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
weight = 6
url = "https://myhugosite.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[params.plausibleAnalytics]
domain = "example.com"
serverURL = "analytics.example.com"

[params.fathomAnalytics]
siteID = "ABCDE"
serverURL = "analytics.example.com"

[languages]

[languages.en]
languagename = "English"

[languages.en.menu]

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "posts/"
weight = 2

[[languages.en.menu.main]]
name = "Projects"
url = "projects/"
weight = 3

[[languages.en.menu.main]]
name = "Contact me"
url = "contact/"
weight = 5

[languages.pt-br]
languagename = "Português"
title = "João Ninguém"

[languages.pt-br.params]
author = "João Ninguém"
info = "Welcome to my website"
description = "Sítio pessoal de João Ninguém"
keywords = "blog,desenvolvedor,pessoal"
footercontent = ""

[languages.pt-br.menu]

[[languages.pt-br.menu.main]]
name = "Sobre"
url = "about/"
weight = 1

[[languages.pt-br.menu.main]]
name = "Blog"
url = "posts/"
weight = 2

[[languages.pt-br.menu.main]]
name = "Projetos"
url = "projects/"
weight = 3

[[languages.pt-br.menu.main]]
name = "Contato"
url = "contact/"
weight = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"